module HerokuJson
  ENV_BLACKLIST = [
      "CODESHIP_ID",
      "CONSOLE_AUTH",
      "DATABASE_URL",
      "ERROR_PAGE_URL",
      "LANG",
      "LIBRARY_PATH",
      "MAINTENANCE_PAGE_URL",
      "MONGOHQ_URL",
      "NEW_RELIC_APP_NAME",
      "NEW_RELIC_ID",
      "NEW_RELIC_LICENSE_KEY",
      "NEW_RELIC_LOG",
      "PATH",
      "PGBACKUPS_URL",
      "PYTHONHASHSEED",
      "PYTHONHOME",
      "PYTHONPATH",
      "PYTHONUNBUFFERED",
      "REDISTOGO_URL",
      "SEARCHBOX_URL",
      "SENTRY_DSN",
      "SHARED_DATABASE_URL",
      "^HEROKU_",
  ]
end
