module HerokuJson
# ENV_WHITELIST = %w{RACK_ENV LANG GEM_PATH}
  ENV_BLACKLIST = %w{ERROR_PAGE_URL MAINTENANCE_PAGE_URL PGBACKUPS_URL HEROKU_POSTGRESQL_COPPER_URL SHARED_DATABASE_URL CONSOLE_AUTH CODESHIP_ID DATABASE_URL MONGOHQ_URL REDISTOGO_URL}
end